---
# tasks file for sa-osquery

  - include: tasks_osquery.yml
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - include: tasks_osquery_rpm.yml
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

